# Generated by Django 3.1 on 2020-08-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200812_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-commented_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-posted_at',)},
        ),
    ]
