# Generated by Django 3.1 on 2020-08-14 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('follow_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_by', to=settings.AUTH_USER_MODEL)),
                ('follow_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Follow Records',
                'ordering': ['-datetime'],
            },
        ),
    ]
