# Generated by Django 3.1 on 2020-08-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20200818_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='semester',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
    ]
