# Generated by Django 3.1 on 2020-08-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200823_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
