# Generated by Django 3.1 on 2020-08-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200813_1328'),
        ('blog', '0002_auto_20200813_1953'),
    ]

    operations = [
    ]
